# Production - uses pre-built image from GitHub Container Registry
# Connects to external Traefik network for reverse proxy

services:
  muddra:
    image: ghcr.io/j4ck3/muddra:latest
    container_name: muddra
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - Urls=http://0.0.0.0:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.muddra.rule=Host(`muddra.com`)"
      - "traefik.http.routers.muddra.entrypoints=websecure"
      - "traefik.http.routers.muddra.tls.certresolver=letsencrypt"
      - "traefik.http.services.muddra.loadbalancer.server.port=8080"
    networks:
      - traefik

networks:
  traefik:
    external: true
